2023-02-03 10:28:55,752 debug message
2023-02-03 10:28:55,753 info
2023-02-03 10:28:55,753 warning
2023-02-03 10:28:55,753 error
2023-02-03 10:28:55,753 critical
2023-02-03 10:28:55,762 [31m[1mWARNING: This is a deve2023-02-03 10:36:39,873 Exception while serving /video_feed
Traceback (most recent call last):
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\waitress\task.py", line 456, in execute
    for chunk in app_iter:
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\wsgi.py", line 500, in __next__
    return self._next()
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\wrappers\response.py", line 50, in _iter_encoded
    for item in iterable:
  File "c:\Users\sanke\OneDrive\Desktop\faee\LineUp\routes\UserRoutes\qrcode.py", line 17, in gen
    data, bbox, rectified_image = qr_detector.detectAndDecode(frame)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\qrcode.cpp:30: error: (-215:Assertion failed) !img.empty() in function 'cv::checkQRInputImage'

2023-02-03 10:37:10,602 Exception while serving /video_feed
Traceback (most recent call last):
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\waitress\task.py", line 456, in execute
    for chunk in app_iter:
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\wsgi.py", line 500, in __next__
    return self._next()
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\wrappers\response.py", line 50, in _iter_encoded
    for item in iterable:
  File "c:\Users\sanke\OneDrive\Desktop\faee\LineUp\routes\UserRoutes\qrcode.py", line 17, in gen
    data, bbox, rectified_image = qr_detector.detectAndDecode(frame)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\qrcode.cpp:30: error: (-215:Assertion failed) !img.empty() in function 'cv::checkQRInputImage'

 "GET /home HTTP/1.1" 200 -
2023-02-03 10:30:23,070 127.0.0.1 - - [03/Feb/2023 10:30:23] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:30:23,102 127.0.0.1 - - [03/Feb/2023 10:30:23] "GET /home HTTP/1.1" 200 -
2023-02-03 10:30:32,489 127.0.0.1 - - [03/Feb/2023 10:30:32] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:30:32,522 127.0.0.1 - - [03/Feb/2023 10:30:32] "GET /home HTTP/1.1" 200 -
2023-02-03 10:30:33,529 127.0.0.1 - - [03/Feb/2023 10:30:33] "[32mGET /logout HTTP/1.1[0m" 302 -
2023-02-03 10:30:33,622 127.0.0.1 - - [03/Feb/2023 10:30:33] "GET /login HTTP/1.1" 200 -
2023-02-03 10:30:44,790 127.0.0.1 - - [03/Feb/2023 10:30:44] "[32mPOST /login HTTP/1.1[0m" 302 -
2023-02-03 10:30:44,945 127.0.0.1 - - [03/Feb/2023 10:30:44] "GET /admin HTTP/1.1" 200 -
2023-02-03 10:30:56,107 127.0.0.1 - - [03/Feb/2023 10:30:56] "[32mPOST /ininitiateslot HTTP/1.1[0m" 302 -
2023-02-03 10:30:56,145 127.0.0.1 - - [03/Feb/2023 10:30:56] "GET /admin HTTP/1.1" 200 -
2023-02-03 10:31:03,178 127.0.0.1 - - [03/Feb/2023 10:31:03] "GET /bookslot HTTP/1.1" 200 -
2023-02-03 10:31:05,652 127.0.0.1 - - [03/Feb/2023 10:31:05] "[32mPOST /bookslot HTTP/1.1[0m" 302 -
2023-02-03 10:31:05,721 127.0.0.1 - - [03/Feb/2023 10:31:05] "GET /bookslot HTTP/1.1" 200 -
2023-02-03 10:31:12,813 127.0.0.1 - - [03/Feb/2023 10:31:12] "GET /admin HTTP/1.1" 200 -
2023-02-03 10:32:26,279 127.0.0.1 - - [03/Feb/2023 10:32:26] "GET /bookslot HTTP/1.1" 200 -
2023-02-03 10:32:28,202 127.0.0.1 - - [03/Feb/2023 10:32:28] "GET /home HTTP/1.1" 200 -
2023-02-03 10:32:29,894 127.0.0.1 - - [03/Feb/2023 10:32:29] "[32mGET /logout HTTP/1.1[0m" 302 -
2023-02-03 10:32:29,922 127.0.0.1 - - [03/Feb/2023 10:32:29] "GET /login HTTP/1.1" 200 -
2023-02-03 10:32:30,969 127.0.0.1 - - [03/Feb/2023 10:32:30] "GET /video_feed HTTP/1.1" 200 -
2023-02-03 10:32:38,129 127.0.0.1 - - [03/Feb/2023 10:32:38] "[32mPOST /login HTTP/1.1[0m" 302 -
2023-02-03 10:32:38,189 127.0.0.1 - - [03/Feb/2023 10:32:38] "GET /home HTTP/1.1" 200 -
2023-02-03 10:32:40,749 127.0.0.1 - - [03/Feb/2023 10:32:40] "GET /video_feed HTTP/1.1" 200 -
2023-02-03 10:32:49,091 127.0.0.1 - - [03/Feb/2023 10:32:49] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:32:49,105 127.0.0.1 - - [03/Feb/2023 10:32:49] "GET /home HTTP/1.1" 200 -
2023-02-03 10:32:59,101 127.0.0.1 - - [03/Feb/2023 10:32:59] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:32:59,122 127.0.0.1 - - [03/Feb/2023 10:32:59] "GET /home HTTP/1.1" 200 -
2023-02-03 10:33:09,078 127.0.0.1 - - [03/Feb/2023 10:33:09] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:33:09,093 127.0.0.1 - - [03/Feb/2023 10:33:09] "GET /home HTTP/1.1" 200 -
2023-02-03 10:33:19,104 127.0.0.1 - - [03/Feb/2023 10:33:19] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:33:19,116 127.0.0.1 - - [03/Feb/2023 10:33:19] "GET /home HTTP/1.1" 200 -
2023-02-03 10:33:29,120 127.0.0.1 - - [03/Feb/2023 10:33:29] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:33:29,145 127.0.0.1 - - [03/Feb/2023 10:33:29] "GET /home HTTP/1.1" 200 -
2023-02-03 10:33:39,117 127.0.0.1 - - [03/Feb/2023 10:33:39] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:33:39,137 127.0.0.1 - - [03/Feb/2023 10:33:39] "GET /home HTTP/1.1" 200 -
2023-02-03 10:33:46,376 Error on request:
Traceback (most recent call last):
  File "c:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "c:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\serving.py", line 324, in execute
    for data in application_iter:
  File "c:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\wsgi.py", line 500, in __next__
    return self._next()
  File "c:\Users\sanke\OneDrive\Desktop\faee\LineUp\venv\lib\site-packages\werkzeug\wrappers\response.py", line 50, in _iter_encoded
    for item in iterable:
  File "C:\Users\sanke\OneDrive\Desktop\faee\LineUp\routes\UserRoutes\qrcode.py", line 17, in gen
    data, bbox, rectified_image = qr_detector.detectAndDecode(frame)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\qrcode.cpp:30: error: (-215:Assertion failed) !img.empty() in function 'cv::checkQRInputImage'
2023-02-03 10:33:49,071 127.0.0.1 - - [03/Feb/2023 10:33:49] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:33:49,125 127.0.0.1 - - [03/Feb/2023 10:33:49] "GET /home HTTP/1.1" 200 -
2023-02-03 10:33:59,084 127.0.0.1 - - [03/Feb/2023 10:33:59] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:33:59,101 127.0.0.1 - - [03/Feb/2023 10:33:59] "GET /home HTTP/1.1" 200 -
2023-02-03 10:34:09,114 127.0.0.1 - - [03/Feb/2023 10:34:09] "[32mGET /confirm_qr HTTP/1.1[0m" 302 -
2023-02-03 10:34:09,127 127.0.0.1 - - [03/Feb/2023 10:34:09] "GET /home HTTP/1.1" 200 -
